var adjectives = [
    'ever',
    'dead',
    'easy',
    'famous',
    'gifted',
    'helpful',
    'important',
    'inexpensive',
    'mushy',
    'odd',
    'powerful',
    'clumsy',
    'defeated',
    'embarrassed',
    'fierce',
    'grumpy',
    'helpless',
    'itchy',
    'jealous',
    'lazy',
    'mysterious',
    'nervous',
    'obnoxious',
    'panicky',
    'repulsive',
    'scary',
    'clean',
    'drab',
    'elegant',
    'fancy',
    'glamorous',
    'handsome',
    'long',
    'magnificent',
    'old-fashioned',
    'plain',
    'quaint',
    'spa',
    'red',
    'orange',
    'yellow',
    'green',
    'blue',
    'purple'
];

var nouns = [
    'mailbox',
    'number',
    'oatmeal',
    'pail',
    'pancake',
    'pear',
    'pest',
    'popcorn',
    'queen',
    'quicksand',
    'quiet',
    'quilt',
    'rainstorm',
    'scarecrow',
    'scarf',
    'jeans',
    'judge',
    'lace',
    'lamp',
    'lettuce',
    'marble',
    'month',
    'north',
    'ocean',
    'patch',
    'plane',
    'playground',
    'kitten',
    'laborer',
    'language',
    'lawyer',
    'linen',
    'locket',
    'lumber',
    'magic',
    'minister',
    'mitten',
    'money',
    'mountain',
    'music',
    'partner',
    'passenger'
];

module.exports = {
    nouns: nouns,
    adjectives: adjectives,
    noun: function() {
        return nouns[Math.floor(Math.random() * nouns.length)];
    },
    adjective: function() {
       return adjectives[Math.floor(Math.random() * adjectives.length)];
    }
};
